#!/usr/bin/env python

# Try to copy text into the clipboard in various ways.

import os, sys, subprocess, base64

def copy_via_xclip(s, enc):
    p = subprocess.Popen(['xclip','-selection','clipboard'], stdin=subprocess.PIPE)
    p.stdin.write(s.encode(enc))
    p.stdin.close()    

def copy_via_osc52(s, enc):
    b = base64.b64encode(s.encode(enc))
    d = b.decode(enc)
    sys.stdout.write('\033]52;c;' + d + '\007')
    sys.stdout.flush()

def copy_via_screen_osc52(s, enc):
    b = base64.b64encode(s.encode(enc))
    d = b.decode(enc)
    sys.stdout.write('\033P\033]52;c;' + d + '\007\033\\')
    sys.stdout.flush()

def copy_via_tmux_osc52(s, enc):
    b = base64.b64encode(s.encode(enc))
    d = b.decode(enc)
    sys.stdout.write('\033Ptmux;\033\033]52;c;' + d + '\007\033\\')
    sys.stdout.flush()

def copy_to_clipboard(txt, enc = None):
    if not enc:
        enc = "UTF-8"

    term = os.getenv("TERM")
    sty = os.getenv("STY")
    ssh_tty = os.getenv("SSH_TTY")
    tmux = os.getenv("TMUX")
    disp = os.getenv("DISPLAY")

    if disp:
        try:
            copy_via_xclip(txt, enc)
            return
        except:
            pass

    if term.startswith("screen"):
        if tmux:
            copy_via_tmux_osc52(txt, enc)
        else:
            copy_via_screen_osc52(txt, enc)

        return

    copy_via_osc52(txt, enc)

if __name__ == "__main__":
    enc = sys.stdin.encoding
    txt = sys.stdin.read()
    copy_to_clipboard(txt, enc)
