#!/bin/bash
ls -d .[^.]*[^~] | grep -vx -e .git -e .urxvt | while read i; do ln -vs $PWD/$i $HOME/$i; done
mkdir ~/bin
ln -s $PWD/copy-to-clipboard ~/bin
mkdir -p ~/.urxvt/ext
for i in 52-osc keyboard-select-emacs border; do ln -s $PWD/.urxvt/ext/$i ~/.urxvt/ext/$i; done

mkdir -p ~/.config/gtk-3.0 ; ln -s $PWD/.config/gtk-3.0/settings.ini ~/.config/gtk-3.0
ls bin/*[^~] | while read i; do ln -vs $PWD/$i $HOME/$i; done
